### PR TITLE
Fix style when applying dark mode

### PR DESCRIPTION
**Pull request by MtBlue81**
## Problem
Difficult to see due to light mode highlight color applied in dark mode.
CleanShot 2022-11-20 at 09 46 23

## Solution
Apply dark mode style removed by #249
CleanShot 2022-11-20 at 09 43 44

### CODE REVIEW

**Comment by h13i32maru** [comment]
Thanks!

**Comment by yosuke-oka** [comment]
This issue is still occurring in 1.1.2 😢 
image

**Comment by MtBlue81** [comment]
@yosuke-oka 
Is the environment GHE or something else?
I only checked in GitHub.com (on Mac Monterey) environment, sorry.

**Comment by yosuke-oka** [comment]
@MtBlue81 
No. In github.com (private repo) on Mac Monterey environment...

**Pull request merged**
